travis:
  secure:
    BINSTAR_TOKEN: hSap7iIDdT1OH81325prIAFNJ/9BoINX3QDBvyQo3BKvAGZ69FP7jnNxRkvssbeVn06HBj6scHskwE/fkmNAyAx1aoJO3IvREwe8Dru/y9SNMA0BHf972teq865y52BNR/pth8argx4iHoo7srAi4HbLfCURyTp9du7+qwqKoNO9qRC89G7Nr7ptdQYMiPR0SEfTn8eBM+ANOs2V85vZdZIAgKdfEst1JF22u5smwk/LQAEcS/Le8TWPer2ky9Gsqk5HdJaAHjAa1gLuM61zPuZdn+uolV7JMNdO+oCK7p8Tqj24JatRzRF7d4W1d4tmI+GoGC4GUKDTNVn7cLtmG9O1TJ6FefOQCxofxDLJFyd9Npl9iVLohiIoQ6kLpF123wcPRILEHz91L7pbRdR3rFYXI+6A+ypANHeAWhZmjTZ3FmEReCKwjqSPMylDWp//6fzCRPwMz7G7rHPMsEXeoPe8+vj4bTJ7XM7J4gUkCIdKOb6FgXdyTKBfZ3g/lR3XOyV1pVaz6xEA00mf9XknftEtJ4AT9kmqexEHWfnqZXzI0YxmyU1eVqn2IJJlP6aYeksaLeFXP1XOnoJYoqTZZkqb5wR0TqUADnY8lABFxGAb8AhNqLEdGy8pFI3EHRPz4oeTo/SbQDgY1urddJI+vGi9pPyIkHGlEcEZ4H+Bu9Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
